### ISSUE TITLE
Create birth plan

### ISSUE THREAD

**Issue by simon31416** [simon31416/chores#37]
See pages 274-276 in the book
See blankett here: http://www.1177.se/Dokument/Stockholms%20l%C3%A4n/Gravid/forlossningsplan_mall.pdf

**Comment by simon31416** [comment]
- Get informed about clamping time of umbilical cord, include in plan.
  http://www.acog.org/Resources-And-Publications/Committee-Opinions/Committee-on-Obstetric-Practice/Timing-of-Umbilical-Cord-Clamping-After-Birth

-> Delayed cord clamping, at least 2 minutes

**Comment by i-vulpi** [comment]
Immediate breastfeeding, ideally around 30min after birth (max 1h). No bottle feeding!
